[features]
seeds = false
[programs.localnet]
solana_validator_dao = "AwyKDr1Z5BfdvK3jX1UWopyjsJSV5cq4cuJpoYLofyEn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/galactus/.config/solana/id.json"

[[test.genesis]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
program = "./deps/spl_governance.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
